
package net.client.order;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "OrderService", targetNamespace = "http://webservices.mailorder.net/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface OrderService {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "generateTrackingNumber", targetNamespace = "http://webservices.mailorder.net/", className = "net.client.order.GenerateTrackingNumber")
    @ResponseWrapper(localName = "generateTrackingNumberResponse", targetNamespace = "http://webservices.mailorder.net/", className = "net.client.order.GenerateTrackingNumberResponse")
    @Action(input = "http://webservices.mailorder.net/OrderService/generateTrackingNumberRequest", output = "http://webservices.mailorder.net/OrderService/generateTrackingNumberResponse")
    public String generateTrackingNumber();

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "saveOrderData", targetNamespace = "http://webservices.mailorder.net/", className = "net.client.order.SaveOrderData")
    @ResponseWrapper(localName = "saveOrderDataResponse", targetNamespace = "http://webservices.mailorder.net/", className = "net.client.order.SaveOrderDataResponse")
    @Action(input = "http://webservices.mailorder.net/OrderService/saveOrderDataRequest", output = "http://webservices.mailorder.net/OrderService/saveOrderDataResponse")
    public void saveOrderData(
        @WebParam(name = "arg0", targetNamespace = "")
        List<String> arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        List<String> arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3);

}
