
package net.client.tracking;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TrackingServiceService", targetNamespace = "http://webservices.mailorder.net/", wsdlLocation = "http://localhost:8080/Mailorder/services/TrackingService?wsdl")
public class TrackingServiceService
    extends Service
{

    private final static URL TRACKINGSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException TRACKINGSERVICESERVICE_EXCEPTION;
    private final static QName TRACKINGSERVICESERVICE_QNAME = new QName("http://webservices.mailorder.net/", "TrackingServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/Mailorder/services/TrackingService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TRACKINGSERVICESERVICE_WSDL_LOCATION = url;
        TRACKINGSERVICESERVICE_EXCEPTION = e;
    }

    public TrackingServiceService() {
        super(__getWsdlLocation(), TRACKINGSERVICESERVICE_QNAME);
    }

    public TrackingServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TRACKINGSERVICESERVICE_QNAME, features);
    }

    public TrackingServiceService(URL wsdlLocation) {
        super(wsdlLocation, TRACKINGSERVICESERVICE_QNAME);
    }

    public TrackingServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TRACKINGSERVICESERVICE_QNAME, features);
    }

    public TrackingServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TrackingServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TrackingService
     */
    @WebEndpoint(name = "TrackingServicePort")
    public TrackingService getTrackingServicePort() {
        return super.getPort(new QName("http://webservices.mailorder.net/", "TrackingServicePort"), TrackingService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TrackingService
     */
    @WebEndpoint(name = "TrackingServicePort")
    public TrackingService getTrackingServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservices.mailorder.net/", "TrackingServicePort"), TrackingService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TRACKINGSERVICESERVICE_EXCEPTION!= null) {
            throw TRACKINGSERVICESERVICE_EXCEPTION;
        }
        return TRACKINGSERVICESERVICE_WSDL_LOCATION;
    }

}
