
package net.client.tracking;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TrackingService", targetNamespace = "http://webservices.mailorder.net/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TrackingService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDataFromTracking", targetNamespace = "http://webservices.mailorder.net/", className = "net.client.tracking.GetDataFromTracking")
    @ResponseWrapper(localName = "getDataFromTrackingResponse", targetNamespace = "http://webservices.mailorder.net/", className = "net.client.tracking.GetDataFromTrackingResponse")
    @Action(input = "http://webservices.mailorder.net/TrackingService/getDataFromTrackingRequest", output = "http://webservices.mailorder.net/TrackingService/getDataFromTrackingResponse")
    public List<String> getDataFromTracking(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
